# Generated by Django 5.0 on 2023-12-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_datedcompleted_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
